spring:
  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      #hbm2ddl.auto: update
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

logging:
  level:
    org.hibernate.SQL: debug

cloud:
  aws:
    s3:
      bucket: beilsang-bucket
      path:
        challenge-main: challenge/main
        challenge-cert: challenge/cert
        member-profile: member-profile
        feed: feed
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

jwt:
  secret-key: ${JWT_SECRET_KEY}

