spring:
  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      #hbm2ddl.auto: update
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database: mysql
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

logging:
  level:
    org.hibernate.SQL: debug

cloud:
  aws:
    s3:
      bucket: beilsang-bucket
      path:
        challenge-main: challenge-main
        feed: feed
        member-profile: member-profile
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

jwt:
  secret-key: qopfmfoesf234fuhvertsv34789yhiuFDSIUFGYDTE18372ksm

#oauth:
#  apple:
#    iss: https://appleid.apple.com
#    client-id: ${OAUTH_APPLE_CLIENT_ID}
#    nonce: ${OAUTH_APPLE_NONCE}